defaults: &defaults
  host: localhost
  allow_dynamic_fields: false

development:
  <<: *defaults
  database: fence_development

test:
  <<: *defaults
  database: fence_test

# set these environment variables on your prod server
production:
  host: flame.mongohq.com
  port: 27084
  username: fence
  password: 85DM!bE;o?7d
  database: fence
  