defaults: &defaults
  host: localhost
  allow_dynamic_fields: false

development:
  <<: *defaults
  database: fence_development

test:
  <<: *defaults
  database: fence_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: <%= ENV['MONGOHQ_URL'] %>
  database: fence_production